#Project 4
#Name: Daniel Shu
#Crossword wordFinder Project Test Functions

import unittest
from funcs import *

class TestCases(unittest.TestCase):
	def testcheckForward(self):
		self.assertAlmostEqual(checkForward(['WAQHGTTWEE', 'CBMIVQQELS', 'AZXWKWIIIL', 'LDWLFXPIPV', 'PONDTMVAMN', 'OEDSOYQGOB', 'LGQCKGMMCT', 'YCSLOACUZM', 'XVDMGSXCYZ', 'UUIUNIXFNU'],"WEE"), True)

	def testcheckBackward(self):
		self.assertAlmostEqual(checkBackward(['UNFXINUIUU', 'ZYCXSGMDVX', 'MZUCAOLSCY', 'TCMMGKCQGL', 'BOGQYOSDEO', 'NMAVMTDNOP', 'VPIPXFLWDL', 'LIIIWKWXZA', 'SLEQQVIMBC', 'EEWTTGHQAW'],"PIP"), True)

	def testcheckDown(self):
		self.assertAlmostEqual(checkDown(['WCALPOLYXU', 'ABZDOEGCVU', 'QMXWNDQSDI', 'HIWLDSCLMU', 'GVKFTOKOGN', 'TQWXMYGASI', 'TQIPVQMCXX', 'WEIIAGMUCF', 'ELIPMOCZYN', 'ESLVNBTMZU'],"LIPMO"), True)

	def testcheckUp(self):
		self.assertAlmostEqual(checkUp(['UZMTBNVLSE', 'NYZCOMPILE', 'FCUMGAIIEW', 'XXCMQVPIQT', 'ISAGYMXWQT', 'NGOKOTFKVG', 'UMLCSDLWIH', 'IDSQDNWXMQ', 'UVCGEODZBA', 'UXYLOPLACW'],"GOKOT"), True)
	
	def testcheckDirection(self):
		self.assertAlmostEqual(checkDirection(['WAQHGTTWEE', 'CBMIVQQELS', 'AZXWKWIIIL', 'LDWLFXPIPV', 'PONDTMVAMN', 'OEDSOYQGOB', 'LGQCKGMMCT', 'YCSLOACUZM', 'XVDMGSXCYZ', 'UUIUNIXFNU'], ['UNFXINUIUU', 'ZYCXSGMDVX', 'MZUCAOLSCY', 'TCMMGKCQGL', 'BOGQYOSDEO', 'NMAVMTDNOP', 'VPIPXFLWDL', 'LIIIWKWXZA', 'SLEQQVIMBC', 'EEWTTGHQAW'], ['WCALPOLYXU', 'ABZDOEGCVU', 'QMXWNDQSDI', 'HIWLDSCLMU', 'GVKFTOKOGN', 'TQWXMYGASI', 'TQIPVQMCXX', 'WEIIAGMUCF', 'ELIPMOCZYN', 'ESLVNBTMZU'], ['UZMTBNVLSE', 'NYZCOMPILE', 'FCUMGAIIEW', 'XXCMQVPIQT', 'ISAGYMXWQT', 'NGOKOTFKVG', 'UMLCSDLWIH', 'IDSQDNWXMQ', 'UVCGEODZBA', 'UXYLOPLACW'], "UNIX"), "(FORWARD)")
	
	def testcheckRow(self):
		self.assertAlmostEqual(checkRow(['WAQHGTTWEE', 'CBMIVQQELS', 'AZXWKWIIIL', 'LDWLFXPIPV', 'PONDTMVAMN', 'OEDSOYQGOB', 'LGQCKGMMCT', 'YCSLOACUZM', 'XVDMGSXCYZ', 'UUIUNIXFNU'], ['UNFXINUIUU', 'ZYCXSGMDVX', 'MZUCAOLSCY', 'TCMMGKCQGL', 'BOGQYOSDEO', 'NMAVMTDNOP', 'VPIPXFLWDL', 'LIIIWKWXZA', 'SLEQQVIMBC', 'EEWTTGHQAW'], ['WCALPOLYXU', 'ABZDOEGCVU', 'QMXWNDQSDI', 'HIWLDSCLMU', 'GVKFTOKOGN', 'TQWXMYGASI', 'TQIPVQMCXX', 'WEIIAGMUCF', 'ELIPMOCZYN', 'ESLVNBTMZU'], ['UZMTBNVLSE', 'NYZCOMPILE', 'FCUMGAIIEW', 'XXCMQVPIQT', 'ISAGYMXWQT', 'NGOKOTFKVG', 'UMLCSDLWIH', 'IDSQDNWXMQ', 'UVCGEODZBA', 'UXYLOPLACW'], "COMPILE"), 6)
	
	def testcheckColumn(self):
		self.assertAlmostEqual(checkColumn(['WAQHGTTWEE', 'CBMIVQQELS', 'AZXWKWIIIL', 'LDWLFXPIPV', 'PONDTMVAMN', 'OEDSOYQGOB', 'LGQCKGMMCT', 'YCSLOACUZM', 'XVDMGSXCYZ', 'UUIUNIXFNU'], ['UNFXINUIUU', 'ZYCXSGMDVX', 'MZUCAOLSCY', 'TCMMGKCQGL', 'BOGQYOSDEO', 'NMAVMTDNOP', 'VPIPXFLWDL', 'LIIIWKWXZA', 'SLEQQVIMBC', 'EEWTTGHQAW'], ['WCALPOLYXU', 'ABZDOEGCVU', 'QMXWNDQSDI', 'HIWLDSCLMU', 'GVKFTOKOGN', 'TQWXMYGASI', 'TQIPVQMCXX', 'WEIIAGMUCF', 'ELIPMOCZYN', 'ESLVNBTMZU'], ['UZMTBNVLSE', 'NYZCOMPILE', 'FCUMGAIIEW', 'XXCMQVPIQT', 'ISAGYMXWQT', 'NGOKOTFKVG', 'UMLCSDLWIH', 'IDSQDNWXMQ', 'UVCGEODZBA', 'UXYLOPLACW'], "UNIX"), 3)
	


# Run the unit tests.
if __name__ == '__main__':
   unittest.main()
